name: "encoder"
platform: "onnxruntime_onnx"

input [
  {
    name: "audio_signal"
    data_type: TYPE_FP32
    dims: [-1, 128, -1]  # [batch_size, 128, time_steps]
  },
  {
    name: "length"
    data_type: TYPE_INT64
    dims: [-1]  # [batch_size]
  }
]

output [
  {
    name: "outputs"
    data_type: TYPE_FP32
    dims: [-1, 1024, -1]  # [batch_size, 1024, time_steps]
  },
  {
    name: "encoded_lengths"
    data_type: TYPE_INT64
    dims: [-1]  # [batch_size]
  }
]

instance_group [
  {
    kind: KIND_GPU
    gpus: [0]
  }
] 