name: "preprocessor"
platform: "onnxruntime_onnx"

input [
  {
    name: "waveforms"
    data_type: TYPE_FP32
    dims: [-1, -1]  # [batch_size, N]
  },
  {
    name: "waveforms_lens"
    data_type: TYPE_INT64
    dims: [-1]  # [batch_size]
  }
]

output [
  {
    name: "features"
    data_type: TYPE_FP32
    dims: [-1, 128, -1]  # [batch_size, 128, T]
  },
  {
    name: "features_lens"
    data_type: TYPE_INT64
    dims: [-1]  # [batch_size]
  }
]

instance_group [
  {
    kind: KIND_CPU
  }
] 