# Prometheus configuration for AMIRA ASR Server monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # AMIRA ASR Server metrics
  - job_name: 'amira-asr-server'
    static_configs:
      - targets: ['amira-asr:8057']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  # Production demo server
  - job_name: 'amira-production-demo'
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s